### Import Libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

from sklearn.compose import ColumnTransformer

from sklearn.pipeline import Pipeline

### Load the Dataset

In [2]:
df = pd.read_csv('../data/raw/heart_disease_data.csv')

### Separate Features and Target

In [6]:
X = df.drop('target', axis=1)
y = df['target']

### Identify feature types

In [9]:
numerical_features = [
    "age",
    "trestbps",
    "chol",
    "thalach",
    "oldpeak",
    "ca"
]

categorical_features = [
    "cp",
    "restecg",
    "slope",
    "thal"
]

binary_features = [
    "sex",
    "fbs",
    "exang"
]

### Train Test Split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [13]:
print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(242, 13)
(61, 13)
(242,)
(61,)

### Should We Scale?

Now comes an important engineering decision.

Different algorithms behave differently.

| Model               | Scale? |
| ------------------- | ------ |
| Logistic Regression | ✅ Yes  |
| KNN                 | ✅ Yes  |
| SVM                 | ✅ Yes  |
| Decision Tree       | ❌ No   |
| Random Forest       | ❌ No   |
| XGBoost             | ❌ No   |

In [14]:
scaler = StandardScaler()

In [15]:
X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

In [16]:
X_train_scaled[numerical_features] = scaler.fit_transform(
    X_train[numerical_features]
)

X_test_scaled[numerical_features] = scaler.transform(
    X_test[numerical_features]
)

In [17]:
X_train[numerical_features].describe().T

          count        mean        std    min     25%    50%     75%    max
age       242.0   54.289256   9.153317   29.0   47.00   55.5   61.00   77.0
trestbps  242.0  131.706612  17.994486   94.0  120.00  130.0  140.00  200.0
chol      242.0  244.884298  47.847387  126.0  211.25  240.0  273.75  409.0
thalach   242.0  150.123967  21.977948   88.0  137.25  152.0  166.00  202.0
oldpeak   242.0    1.071901   1.206258    0.0    0.00    0.8    1.80    6.2
ca        242.0    0.743802   1.042889    0.0    0.00    0.0    1.00    4.0

In [18]:
X_train_scaled[numerical_features].describe().T

,count,mean,std,min,25%,50%,75%,max
age,242.0,3.523352e-16,1.002073,-2.768578,-0.798002,0.132548,0.734668,2.486291
trestbps,242.0,2.642514e-16,1.002073,-2.099797,-0.651915,-0.095037,0.461840,3.803105
chol,242.0,-1.541467e-16,1.002073,-2.489806,-0.704406,-0.102292,0.604537,3.437091
thalach,242.0,-3.963771e-16,1.002073,-2.832508,-0.586981,0.085537,0.723859,2.365259
oldpeak,242.0,1.481827e-16,1.002073,-0.890458,-0.890458,-0.225876,0.604853,4.260057
ca,242.0,2.202095e-17,1.002073,-0.714691,-0.714691,-0.714691,0.246171,3.128758

In [19]:
numeric_transformer = Pipeline(
    steps=[
        ("scaler", StandardScaler())
    ]
)


preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numerical_features)
    ],
    remainder="passthrough"
)